---
title: "Lower Drinking Ages -> Higher Tax Revenues?"
description: |
  Unconsidered Sin Tax?
author:
  - name: Jacob Ford
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---


**Draft**

Premise: I live in Canada now. The drinking age is 19, what is the estimated tax revenue omitted in the United States from a drinking age of 21? 

One of my favorite courses in graduate school was an overview of American state legislatures taught by the fantastic [Chris Ross](https://en.wikipedia.org/wiki/L._Chris_Ross), member of the Pennsylvania House of Representatives for six terms. At the end of the course, we simulated the creation of the Pennsylvania state budget for a given year, debating which programs would be funded or cut, how to make sensible negotiations with political opponents, and more concretely, just how many gold egotts would be dropped off at those troublesome [mavericks](https://www.someecards.com/usercards/viewcard/4d298cbd0b9fb7779b47b224fc6e38d86b/).  

Sin taxes were all the rage at the time. Specifically, increasing state taxes on liquor (if you're not from Pennsylvania, you need to know just how strict liquor laws once were, so this idea had some traction), tobacco, or state lotteries. The idea of dropping the drinking age below 21 would have surely resulted in a public stoning, but what if it makes fiscal sense? 


## The Northern Example

