---
title: "Good Eatin's: Toronto "
author:
  - name: Jacob Ford
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---

# Toronto Food Recommendations

Updated in January 2025, after several weeks of new parental life. We've been lucky enough to eat out quite a bit, with a few new favorites joining the ranks on the list. 


```{r setup, include=FALSE}

# In June of 2023, we moved from Durham, North Carolina to Toronto, Ontario, Canada. Home of:
# 
# - 2.93 million, 5.9 in the greater Toronto area (4th largest in North America)
# - alphanumeric zip codes
# - 'washrooms' 
# - Tim Hortons
# - dog parks a-plenty
# - a big lovely lake
# - universal health care (*american sigh*)
# - Abbreviations: Raps not the Raptors, the Jays not the Blue Jays, blend in people
# 
# But most importantly for this post's consideration is what must be a world record of most micro-worlds held within one metropolitan area. 
# 
# Little India, Chinatown (actually there are two Chinatowns), Little Japan, Little Tibet, Little Italy, Little Portugal, Little Malta, Little Jamaica, Greektown, Koreatown. And then there are the fusion spinoffs, my personal favorite being Rasta Pasta (Jamaican-Italian) and the Hungary Thai (ya get it?), along with countless Hakka Indian-Carribean fusion on poutine spots. The evidence that God exists is the holiest dish on earth: jerk chicken on poutine, see below on Queen Street. 
# 
# It's an amazingly diverse, multicultural menagerie of a city. 
# 
# 
# 
# You know the drill, given our very limited time here so far, only the absolute must don't-miss-these spots are below. Enjoy :) 
# 


library(dplyr)
library(leaflet)
library(sf)


library(leaflet)
library(RColorBrewer)
library(readxl)
eats_data <- read_excel("Eat_Data.xlsx")



```





```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height = 10, fig.width=10}

# Define a color palette for genres
pal <- colorFactor(
  palette = "Dark2",
  domain = eats_data$Genre
)

# Create the map
eats_map <- leaflet(data = eats_data) %>%
  addProviderTiles("CartoDB.Positron")

# Add the "Show All" group (includes all categories)
eats_map <- eats_map %>%
  addCircles(
    data = eats_data,
    lat = ~Latitutde, 
    lng = ~Longitude,
    popup = ~paste("Name: ", Name, "<br>",
                   "Genre: ", Genre, "<br>",
                   "Don't you dare miss: ", `Don't Miss:`),
    color = ~pal(Genre),
    weight = 10,
    fillOpacity = 0.8,
    group = "Show All"
  )

# Add each genre as a separate base group
unique_genres <- unique(eats_data$Genre)
for (genre in unique_genres) {
  genre_data <- subset(eats_data, Genre == genre)
  eats_map <- eats_map %>%
    addCircles(
      data = genre_data,
      lat = ~Latitutde, 
      lng = ~Longitude,
      popup = ~paste("Name: ", Name, "<br>",
                     "Genre: ", Genre, "<br>",
                     "Don't you dare miss: ", `Don't Miss:`),
      color = ~pal(Genre),
      weight = 10,
      fillOpacity = 0.8,
      group = genre
    )
}

# Add a dropdown menu for base groups
eats_map <- eats_map %>%
  addLayersControl(
    baseGroups = c("Show All", unique_genres),
    options = layersControlOptions(collapsed = FALSE)
  )

# Display the map
eats_map

```








