---
title: "Good Eatin's"
description: |
  The hidden gems I didn't want to share
author:
  - name: Jacob Ford
    url: https://jford-dchcmpo.github.io/Blog/posts/2021-12-30-Redistricting-and-Racial-Targetting/
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---

Click on a location, get my 'don't miss' item(s) from each. 

March 2023 Update: We finally got to Zweli's, America's first Zimbabwean restaurant, owned and operated by the indomitable Williams duo. 10/10, we'll certainly be back to try to oxtail which quickly sells out. Perhaps the happiest surprise: their lemonade was outstanding and almost worth a return journey alone!  





```{r setup, include=FALSE}
library(dplyr)
library(leaflet)
library(sf) 

library(readxl)
eats_data <- read_excel("Eat_Data.xlsx")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(RColorBrewer)
pal <- colorFactor(
  palette = 'Dark2',
  domain = eats_data$Genre
)


eats_map <- leaflet(data=eats_data) %>%
 # addTiles() %>%
 addProviderTiles("CartoDB.Positron") %>%
  addCircles(lat = eats_data$Latitutde, lng=eats_data$Longitude,
             popup=paste("Name: ", eats_data$Name, "<br>",
                          "Genre: ", eats_data$Genre, "<br>",
                          "Don't you dare miss: ", eats_data$`Don't Miss:`),
             color = ~pal(Genre),
             weight=10,
             fillOpacity = 2) %>%
  addLegend("bottomleft",
            pal=pal,
            values=~Genre) 
  


eats_map
```





```{r echo=FALSE, message=FALSE, warning=FALSE}


# Assuming your eats_data has these columns: Genre, Latitutde, Longitude, Name, Don't Miss:

pal <- colorFactor(
palette = 'Dark2',
  domain = eats_data$Genre
)

eats_map <- leaflet(data = eats_data) %>%
  addProviderTiles("CartoDB.Positron")

# Add each genre as a separate layer
unique_genres <- unique(eats_data$Genre)
for (genre in unique_genres) {
  genre_data <- subset(eats_data, Genre == genre)
  eats_map <- eats_map %>%
    addCircles(
      data = genre_data,
      lat = ~Latitutde, 
      lng = ~Longitude,
      popup = ~paste("Name: ", Name, "<br>",
                     "Genre: ", Genre, "<br>",
                     "Don't you dare miss: ", `Don't Miss:`),
      color = ~pal(Genre),
      weight = 10,
      fillOpacity = 2,
      group = genre
    )
}

# Add a layer control
eats_map <- eats_map %>%
  addLayersControl(
    overlayGroups = unique_genres,
    options = layersControlOptions(collapsed = FALSE)
  
  ) %>%
  addLegend(
    "bottomleft",
    pal = pal,
    values = ~Genre
  )

eats_map


```

